import { mkdtempSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { gzipSync } from "node:zlib";
import { afterAll, describe, expect, it } from "vitest";
import { AUDIT_LIMITS, SUBJECT } from "../scripts/staging-ops/image-audit/subject.mjs";
import { sha256, verifyManifest } from "../scripts/staging-ops/image-audit/layers.mjs";
import { inspectExport, latestAppMembers } from "../scripts/staging-ops/image-audit/inspect.mjs";
import {
  compareInventory,
  dockerignoreMatcher,
  expectedInventory,
  inventorySummary,
  provenanceCategory,
} from "../scripts/staging-ops/image-audit/expected-tree.mjs";
import { buildTar, syntheticSecret } from "./helpers/tar-fixture";

/**
 * PUB-07's local synthetic-image integration test: a hand-built export archive driven through the
 * exact code the runner runs — no Docker, no registry, no network.
 *
 * THE CLAIM IT SUPPORTS, precisely. That the inspector reads every layer's content, including a file
 * a later layer deletes, and stages it where a scanner would see it. It does NOT claim a scan ran,
 * and it says nothing whatsoever about the real pinned digest: these are generated bytes, and
 * "MOCK PASS IS NOT THE LIVE AUDIT" is the spec's own line.
 *
 * Every secret-shaped value here is minted per run by `syntheticSecret`, so this file cannot become
 * a place a real credential hides.
 */

/** The shapes this file reads off the inspector's result. Narrow on purpose: no `any` in a fixture. */
interface LayerSummary {
  index: number;
  form: string;
  members: number;
  expandedBytes: number;
}
interface InventoryMember {
  path: string;
  type: string;
  sha256?: string;
}
interface ComparisonOutcome {
  path: string;
  outcome: string;
}

const scratches: string[] = [];
const scratch = () => {
  const dir = mkdtempSync(join(tmpdir(), "aios-audit-test-"));
  scratches.push(dir);
  return dir;
};
afterAll(() => { for (const dir of scratches) rmSync(dir, { recursive: true, force: true }); });

/** Assemble a synthetic single-platform image and its `docker save`-shaped export. */
function synthesizeImage(layerTars: Buffer[], options: { env?: string[]; history?: string[]; uncompressed?: boolean } = {}) {
  const blobs = layerTars.map((tar) => (options.uncompressed ? tar : gzipSync(tar)));
  const config = {
    architecture: "amd64",
    os: "linux",
    config: {
      Env: options.env ?? ["PATH=/usr/local/bin", "NODE_ENV=production"],
      Entrypoint: ["/usr/bin/tini", "-s", "--", "node"],
      User: "node",
      Labels: {
        "org.opencontainers.image.revision": SUBJECT.sourceRevision,
        "org.opencontainers.image.source": `https://github.com/${SUBJECT.repository}`,
      },
    },
    history: (options.history ?? ["RUN npm ci --ignore-scripts"]).map((created_by) => ({ created_by })),
    rootfs: { type: "layers", diff_ids: layerTars.map((tar) => sha256(tar)) },
  };
  const configBytes = Buffer.from(JSON.stringify(config), "utf8");
  const manifest = {
    schemaVersion: 2,
    mediaType: "application/vnd.oci.image.manifest.v1+json",
    config: { mediaType: "application/vnd.oci.image.config.v1+json", digest: sha256(configBytes), size: configBytes.length },
    layers: blobs.map((blob) => ({
      mediaType: options.uncompressed ? "application/vnd.oci.image.layer.v1.tar" : "application/vnd.oci.image.layer.v1.tar+gzip",
      digest: sha256(blob),
      size: blob.length,
    })),
  };
  const manifestBytes = Buffer.from(JSON.stringify(manifest), "utf8");
  // The export names its blobs however the local store likes — the inspector never reads these names,
  // it looks members up by hash, so deliberately unhelpful names are the honest fixture.
  const exportTar = buildTar([
    { name: "oci-layout", content: '{"imageLayoutVersion":"1.0.0"}' },
    { name: "blobs/sha256/aaaaaaaa", content: configBytes },
    ...blobs.map((blob, index) => ({ name: `blobs/sha256/zzzz${index}`, content: blob })),
  ]);
  return { manifestBytes, manifestDigest: sha256(manifestBytes), exportTar, configBytes, blobs };
}

async function inspect(image: ReturnType<typeof synthesizeImage>) {
  const dir = scratch();
  const exportPath = join(dir, "image.tar");
  writeFileSync(exportPath, image.exportTar);
  const manifest = verifyManifest(image.manifestBytes, image.manifestDigest);
  const result = await inspectExport({ exportPath, manifest, scratchDir: dir, limits: AUDIT_LIMITS, platform: "linux/amd64" });
  return { ...result, dir };
}

/** Everything the scanner would be pointed at, as one string. The scan surface, measured. */
function scanSurface(scanDir: string): string {
  const walk = (dir: string): string[] => readdirSync(dir).flatMap((entry) => {
    const full = join(dir, entry);
    return statSync(full).isDirectory() ? walk(full) : [readFileSync(full, "utf8")];
  });
  return walk(scanDir).join("\n");
}

describe("a clean synthetic image passes, and the pass is measured (PUB-07)", () => {
  it("verifies identity, inventories every layer, and reports complete coverage", async () => {
    const image = synthesizeImage([
      buildTar([{ name: "app/package.json", content: '{"name":"aios"}' }]),
      buildTar([{ name: "app/index.js", content: "export const ok = true;\n" }]),
    ]);
    const result = await inspect(image);
    expect(result.identityVerified).toBe(true);
    expect(result.layers.map((layer: LayerSummary) => layer.form)).toEqual(["compressed-blob", "compressed-blob"]);
    expect(result.coverage.complete).toBe(true);
    expect(result.coverage.limitations).toEqual([]);
    // A clean pass that read NOTHING would look identical without this: coverage counts are the
    // negative control on the whole result.
    expect(result.coverage.members).toBe(2);
    expect(result.coverage.stagedBytes).toBeGreaterThan(0);
    expect(latestAppMembers(result.appMembers, result.merged).map((m: InventoryMember) => m.path).sort())
      .toEqual(["app/index.js", "app/package.json"]);
  });

  /**
   * THE DEFECT THIS EXISTS FOR. The decode branch was chosen by asking whether the export contained a
   * member hashing to `descriptor.digest`. For an uncompressed `…layer.v1.tar` layer that digest IS
   * the diff_id, so the answer was yes for a plain tar — and the raw tar went to gunzip, which failed
   * with `incorrect header check`. The media type is what says how the bytes are encoded.
   */
  it("reads an UNCOMPRESSED-diff export the same way, without attempting a decode", async () => {
    const image = synthesizeImage([buildTar([{ name: "app/index.js", content: "ok" }])], { uncompressed: true });
    // The precondition that made the old branch fire: for this media type the two digests coincide.
    const manifest = JSON.parse(image.manifestBytes.toString("utf8"));
    expect(manifest.layers[0].mediaType).toBe("application/vnd.oci.image.layer.v1.tar");
    expect(manifest.layers[0].digest).toBe(sha256(image.blobs[0]));

    const result = await inspect(image);
    expect(result.layers[0].form).toBe("uncompressed-diff");
    expect(result.coverage.complete).toBe(true);
    // …and the content really was read, rather than the layer being skipped into a clean-looking pass.
    expect(result.coverage.members).toBe(1);
    expect(scanSurface(result.scanDir)).toContain("ok");
  });

  it("FAILS an uncompressed layer whose descriptor digest is not its diff_id", async () => {
    // A tar layer's blob digest and diff_id are the same bytes by definition. A manifest/config pair
    // that disagrees is inconsistent, and guessing which one to believe is how an audit ends up
    // describing an artifact it did not read.
    const image = synthesizeImage([buildTar([{ name: "app/index.js", content: "ok" }])], { uncompressed: true });
    const config = JSON.parse(image.configBytes.toString("utf8"));
    config.rootfs.diff_ids = [sha256(Buffer.from("some other layer"))];
    const configBytes = Buffer.from(JSON.stringify(config), "utf8");
    const manifest = JSON.parse(image.manifestBytes.toString("utf8"));
    manifest.config.digest = sha256(configBytes);
    manifest.config.size = configBytes.length;
    const manifestBytes = Buffer.from(JSON.stringify(manifest), "utf8");

    const dir = scratch();
    const exportPath = join(dir, "image.tar");
    writeFileSync(exportPath, buildTar([
      { name: "blobs/sha256/aaaaaaaa", content: configBytes },
      { name: "blobs/sha256/zzzz0", content: image.blobs[0] },
    ]));
    await expect(inspectExport({
      exportPath,
      manifest: verifyManifest(manifestBytes, sha256(manifestBytes)),
      scratchDir: dir,
      limits: AUDIT_LIMITS,
      platform: "linux/amd64",
    })).rejects.toThrow(/is not its diff_id/);
  });
});

describe("a secret deleted by a later layer is INVISIBLE merged and still scanned (PUB-02, PUB-07)", () => {
  it("stages the earlier layer's bytes for the scanner and reports the path as shadowed", async () => {
    const secret = syntheticSecret();
    const image = synthesizeImage([
      buildTar([
        { name: "app/index.js", content: "export const ok = true;\n" },
        { name: "app/credentials.json", content: `{"token":"${secret}"}` },
      ]),
      // The later layer deletes it. `docker run` + `cat` would find nothing; the layer blob still
      // ships the bytes to everyone who pulls the digest.
      buildTar([{ name: "app/.wh.credentials.json" }]),
    ]);
    const result = await inspect(image);

    // (1) Invisible in the merged filesystem — the view an inspected container would show.
    expect(result.merged.visible.has("app/credentials.json")).toBe(false);
    expect(result.merged.shadowed).toContainEqual({ path: "app/credentials.json", layer: 0, removedBy: 1, reason: "deleted" });

    // (2) …and PRESENT on the scan surface anyway. This is the whole audit in one assertion.
    expect(scanSurface(result.scanDir)).toContain(secret);

    // (3) The two sets are DIFFERENT, and that is the point. `/app` for the provenance comparison is
    // what survives — a deleted path is not a provenance question about the image's file tree — while
    // the scan above covered the bytes that still ship. A `latestAppMembers` that took the last
    // WRITER instead of the surviving member would put `app/credentials.json` back in this list.
    const shipped = latestAppMembers(result.appMembers, result.merged).map((m: InventoryMember) => m.path);
    expect(shipped).toEqual(["app/index.js"]);
    expect(shipped).not.toContain("app/credentials.json");
  });

  it("does the same for a file OVERWRITTEN by a later layer", async () => {
    const oldSecret = syntheticSecret();
    const image = synthesizeImage([
      buildTar([{ name: "app/.env.local", content: `TOKEN=${oldSecret}` }]),
      buildTar([{ name: "app/.env.local", content: "TOKEN=redacted-later" }]),
    ]);
    const result = await inspect(image);
    expect(result.merged.visible.get("app/.env.local")).toBe(1);
    expect(scanSurface(result.scanDir)).toContain(oldSecret);
  });
});

describe("the image CONFIG and HISTORY are scanned content, not metadata (PUB-03)", () => {
  it("stages Env values for the scanner", async () => {
    const secret = syntheticSecret("ghs_");
    const image = synthesizeImage([buildTar([{ name: "app/index.js", content: "ok" }])], {
      env: ["PATH=/usr/local/bin", `REGISTRY_TOKEN=${secret}`],
    });
    const result = await inspect(image);
    expect(readFileSync(join(result.scanDir, "image-config.json"), "utf8")).toContain(secret);
  });

  it("stages history `created_by` lines for the scanner", async () => {
    const secret = syntheticSecret("github_pat_");
    const image = synthesizeImage([buildTar([{ name: "app/index.js", content: "ok" }])], {
      history: ["RUN npm ci", `RUN curl -H "Authorization: Bearer ${secret}" https://example.invalid`],
    });
    const result = await inspect(image);
    expect(scanSurface(result.scanDir)).toContain(secret);
  });
});

describe("coverage gaps are REPORTED, never silently narrowed (PUB-03)", () => {
  it("records an unexpandable archive format instead of calling opaque bytes inspected", async () => {
    const image = synthesizeImage([buildTar([{ name: "app/vendor/bundle.zip", content: "PK opaque" }])]);
    const result = await inspect(image);
    expect(result.coverage.complete).toBe(false);
    expect(result.coverage.limitations).toContainEqual({ kind: "unexpanded-archive-format", layer: 0, extension: ".zip" });
  });

  it("records an oversized member instead of scanning a truncated copy of it", async () => {
    const image = synthesizeImage([buildTar([{ name: "app/big.bin", content: Buffer.alloc(4096, 7) }])]);
    const dir = scratch();
    const exportPath = join(dir, "image.tar");
    writeFileSync(exportPath, image.exportTar);
    const manifest = verifyManifest(image.manifestBytes, image.manifestDigest);
    const result = await inspectExport({
      exportPath, manifest, scratchDir: dir, platform: "linux/amd64",
      limits: { ...AUDIT_LIMITS, maxMemberBytes: 1024 },
    });
    expect(result.coverage.complete).toBe(false);
    expect(result.coverage.limitations).toContainEqual({ kind: "oversized-member", layer: 0, bytes: 4096 });
  });

  it("records an unknown member TYPE instead of passing over bytes nobody inspected", async () => {
    const image = synthesizeImage([buildTar([
      { name: "app/index.js", content: "ok" },
      { name: "app/odd", content: "unread bytes", rawTypeflag: "M" },
    ])]);
    const result = await inspect(image);
    expect(result.coverage.complete).toBe(false);
    expect(result.coverage.limitations).toContainEqual({ kind: "unsupported-member-type", layer: 0, typeflag: "M" });
  });

  it("does not echo an attacker-chosen typeflag into the evidence", async () => {
    // One attacker-controlled byte, and limitations reach the PUBLIC artifact. Non-printables are
    // reported by category rather than passed through.
    //
    // Written as an escape, never as a literal control byte in this file: a raw non-printable is
    // invisible in review, and one byte over (`\0`) would make git treat the source as binary.
    const image = synthesizeImage([buildTar([{ name: "app/odd", content: "x", rawTypeflag: String.fromCharCode(1) }])]);
    const result = await inspect(image);
    expect(result.coverage.limitations).toContainEqual({ kind: "unsupported-member-type", layer: 0, typeflag: "non-printable" });
  });

  it("EXPANDS a nested tar.gz so its contents reach the scanner", async () => {
    const secret = syntheticSecret();
    const nested = gzipSync(buildTar([{ name: "fixture/key.txt", content: secret }]));
    const image = synthesizeImage([buildTar([{ name: "app/node_modules/pkg/test.tar.gz", content: nested }])]);
    const result = await inspect(image);
    // Left opaque, this file is gzip bytes and every rule reports clean. The expansion is the
    // difference between scanning a package and scanning its wrapper.
    expect(scanSurface(result.scanDir)).toContain(secret);
  });

  /**
   * PUB-01's CUMULATIVE bound. Each layer here is comfortably inside `maxExpandedBytesPerLayer`, and
   * together they exceed the total — which is the case a per-layer limit cannot catch, and the reason
   * "64 layers × 6 GiB" was never actually bounded.
   */
  it("stops staging at the TOTAL byte bound, even when every layer is individually within its limit", async () => {
    const perLayer = 4096;
    const image = synthesizeImage([
      buildTar([{ name: "app/first.bin", content: Buffer.alloc(perLayer, 1) }]),
      buildTar([{ name: "app/second.bin", content: Buffer.alloc(perLayer, 2) }]),
    ]);
    const dir = scratch();
    const exportPath = join(dir, "image.tar");
    writeFileSync(exportPath, image.exportTar);
    const result = await inspectExport({
      exportPath,
      manifest: verifyManifest(image.manifestBytes, image.manifestDigest),
      scratchDir: dir,
      platform: "linux/amd64",
      limits: {
        ...AUDIT_LIMITS,
        // Each layer is allowed its whole content; the RUN is allowed only the first one's worth.
        maxExpandedBytesPerLayer: perLayer * 4,
        maxMemberBytes: perLayer * 4,
        maxTotalStagedBytes: perLayer + 1,
      },
    });

    expect(result.coverage.complete).toBe(false);
    expect(result.coverage.limitations).toContainEqual({ kind: "total-staging-budget-exhausted", layer: 1 });
    // The FIRST layer is unaffected — a total bound must stop staging, not retroactively invalidate
    // what was already read.
    expect(result.coverage.stagedBytes).toBe(perLayer);
    expect(scanSurface(result.scanDir)).toContain(Buffer.alloc(perLayer, 1).toString("utf8"));
    // …and the refused member left NO partial file behind for the scanner to read as a whole one.
    expect(scanSurface(result.scanDir)).not.toContain(Buffer.alloc(1, 2).toString("utf8"));
    // Identity is still verified for every layer: the bound is about how much content was staged,
    // not about which layers exist.
    expect(result.layers).toHaveLength(2);
  });

  it("counts a NESTED archive's expansion against the same total bound", async () => {
    const secret = syntheticSecret();
    const nested = gzipSync(buildTar([{ name: "fixture/key.txt", content: secret }]));
    const image = synthesizeImage([buildTar([
      { name: "app/a.js", content: "x".repeat(64) },
      { name: "app/node_modules/pkg/test.tar.gz", content: nested },
    ])]);
    const dir = scratch();
    const exportPath = join(dir, "image.tar");
    writeFileSync(exportPath, image.exportTar);
    const result = await inspectExport({
      exportPath,
      manifest: verifyManifest(image.manifestBytes, image.manifestDigest),
      scratchDir: dir,
      platform: "linux/amd64",
      // Enough for the two layer members, not for the inflated copy of the nested archive: an
      // expansion that ignored the budget is how a decompression bomb fills a runner disk.
      limits: { ...AUDIT_LIMITS, maxTotalStagedBytes: 64 + nested.length },
    });
    expect(result.coverage.limitations).toContainEqual({ kind: "total-staging-budget-exhausted", layer: 0 });
    expect(scanSurface(result.scanDir)).not.toContain(secret);
  });

  it("FAILS a missing layer rather than auditing the layers it did find", async () => {
    const image = synthesizeImage([
      buildTar([{ name: "app/a.js", content: "1" }]),
      buildTar([{ name: "app/b.js", content: "2" }]),
    ]);
    // Drop the second blob from the export, leaving the manifest still declaring two layers. The
    // FIRST blob is reused verbatim, so the only difference from the passing case is the absence —
    // re-gzipping it would risk failing for a byte-level reason this case is not about.
    const dir = scratch();
    const exportPath = join(dir, "image.tar");
    const manifest = verifyManifest(image.manifestBytes, image.manifestDigest);
    writeFileSync(exportPath, buildTar([
      { name: "blobs/sha256/aaaaaaaa", content: image.configBytes },
      { name: "blobs/sha256/zzzz0", content: image.blobs[0] },
    ]));
    await expect(inspectExport({ exportPath, manifest, scratchDir: dir, limits: AUDIT_LIMITS, platform: "linux/amd64" }))
      .rejects.toThrow(/missing layer/);
  });
});

describe("the /app inventory: dockerignore filters the EXPECTED set only (M1)", () => {
  const dockerignore = ["node_modules", ".next", ".git", ".env", ".env.*", "!.env.example", ".context", "*.log"].join("\n");
  const sourceEntries = [
    { path: "package.json", type: "file", sha256: sha256(Buffer.from("{}")).slice(7) },
    { path: "lib/index.ts", type: "file", sha256: sha256(Buffer.from("export {}")).slice(7) },
    { path: ".env.example", type: "file", sha256: sha256(Buffer.from("KEY=")).slice(7) },
    { path: ".env.production", type: "file", sha256: "deadbeef" },
    { path: ".context/notes.md", type: "file", sha256: "cafebabe" },
  ];

  it("honours last-match-wins negation, so `.env.example` is expected and `.env.production` is not", () => {
    const excluded = dockerignoreMatcher(dockerignore);
    expect(excluded(".env.example")).toBe(false);
    expect(excluded(".env.production")).toBe(true);
    expect(excluded("node_modules/react/index.js")).toBe(true);
    expect(excluded(".context/notes.md")).toBe(true);
    expect(excluded("lib/index.ts")).toBe(false);
  });

  it("calls an EXCLUDED path present in the image a FINDING, never a scan skip", () => {
    const expected = expectedInventory(sourceEntries, dockerignore);
    const comparison = compareInventory([
      { path: "app/package.json", type: "file", sha256: sourceEntries[0].sha256 },
      // The two paths `.dockerignore` said would never be in the context. If exclusions filtered the
      // ACTUAL set, these would vanish from the report — the exact inversion M1 rules out.
      { path: "app/.env.production", type: "file", sha256: "deadbeef" },
      { path: "app/.context/notes.md", type: "file", sha256: "cafebabe" },
    ], expected);
    const outcomes = Object.fromEntries(comparison.outcomes.map((o: ComparisonOutcome) => [o.path, o.outcome]));
    expect(outcomes["app/.env.production"]).toBe("excluded-path");
    expect(outcomes["app/.context/notes.md"]).toBe("excluded-path");
    expect(outcomes["app/package.json"]).toBe("matched");
  });

  it("flags a first-party file whose bytes differ from the Git blob", () => {
    const expected = expectedInventory(sourceEntries, dockerignore);
    const comparison = compareInventory([{ path: "app/lib/index.ts", type: "file", sha256: "0".repeat(64) }], expected);
    expect(comparison.outcomes[0].outcome).toBe("content-mismatch");
  });

  it("accounts for dependencies and build output as CATEGORIES, which are not exemptions", () => {
    // Accounting explains why a path has no Git blob. It does not remove the file from the scan —
    // that surface is proved separately by the nested-archive case above.
    expect(provenanceCategory("app/node_modules/react/index.js")).toBe("npm-dependency");
    expect(provenanceCategory("app/node_modules/.package-lock.json")).toBe("npm-dependency");
    expect(provenanceCategory("app/.next/BUILD_ID")).toBe("next-build-dir");
    expect(provenanceCategory("app/src/unexpected-generated.js")).toBeUndefined();
  });

  it("reports an unexpected generated path and a missing expected path as findings", () => {
    const expected = expectedInventory(sourceEntries, dockerignore);
    const summary = inventorySummary(compareInventory([
      { path: "app/package.json", type: "file", sha256: sourceEntries[0].sha256 },
      { path: "app/build-artifact.bin", type: "file", sha256: "abc" },
    ], expected));
    expect(summary.counts.unexpected).toBe(1);
    // `.env.example` and `lib/index.ts` were expected and absent — the comparison is INCOMPLETE, and
    // an incomplete comparison must not read as a clean one.
    expect(summary.counts.missing).toBe(2);
    expect(summary.complete).toBe(false);
    expect(summary.findings).toBe(3);
  });

  it("compares symlinks as links, without following them", () => {
    const expected = expectedInventory(
      [{ path: "bin/cli", type: "symlink", linkTarget: "../lib/cli.js" }],
      dockerignore,
    );
    const same = compareInventory([{ path: "app/bin/cli", type: "symlink", linkTarget: "../lib/cli.js" }], expected);
    const moved = compareInventory([{ path: "app/bin/cli", type: "symlink", linkTarget: "/etc/passwd" }], expected);
    expect(same.outcomes[0].outcome).toBe("matched");
    expect(moved.outcomes[0].outcome).toBe("content-mismatch");
  });
});
