-- NEUTERED by PRET-6 (docs/design/pret6-retirement.md §2.1 — the replay-demands-editing rule
-- postgres/migrations/README.md sanctions). This file originally created
-- `teams.access_enforcement` ('permissive' default) — the Phase B rollout flag. Left as DML-free
-- history because pg-load-schema replays every migration on every deploy: re-creating the column
-- after 20260818210000 dropped it would re-default every team to permissive and wedge that
-- migration's refusing precondition forever (the cold-read H1 fleet-bricker). The flag's whole
-- life: created here (2026-08-11) → auto-flip era (PRET-2, 20260817120000) → retired
-- (20260818210000). Enforcing is the only behavior now; membership is the sole access model.
