-- NEUTERED by PRET-6 (docs/design/pret6-retirement.md §2.1, same rule as
-- 20260811160000_access_enforcement_flag.sql). Originally created `teams.autoflip_hold` — the
-- PRET-2 operator-undo hold, control state written atomically with the mode change. Retired
-- with the whole flip subsystem by 20260818210000 (which drops both columns behind the
-- refusing precondition); re-creating it on replay would resurrect a column nothing reads.
