#!/usr/bin/env bash
#
# Copy a canonical .claude/skills/<name>/ skill into the other three agent
# runtimes this repo supports, so Codex, Opencode, and Cursor can use it too.
#
# .claude/skills/<name>/SKILL.md stays the single source of truth. This script
# only ever writes generated copies — never hand-edit the output paths below.
#
# Mirrors the copy-verbatim convention already used by
# aios-engineering-harness's adapters (`cp -R .harness/skills/. .agents/skills/`
# for Codex, `.opencode/skills/` for Opencode) and the generated-Cursor-rule
# pattern in adapters/cursor (`.cursor/rules/harness-context.mdc`).
#
# Usage: bash scripts/sync-skill-runtimes.sh <skill-name>

set -euo pipefail

SKILL_NAME="${1:?usage: sync-skill-runtimes.sh <skill-name>}"
[[ "$SKILL_NAME" =~ ^[A-Za-z0-9_-]+$ ]] || {
  echo "sync-skill-runtimes: '<skill-name>' must be a bare directory name (letters/digits/-/_ only), got '$SKILL_NAME'" >&2
  exit 1
}
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/.claude/skills/$SKILL_NAME"

if [[ ! -f "$SRC/SKILL.md" ]]; then
  echo "sync-skill-runtimes: no $SRC/SKILL.md — nothing to sync" >&2
  exit 1
fi

sync_copy() {
  local dest="$1"
  mkdir -p "$(dirname "$dest")"
  rm -rf "$dest"
  mkdir -p "$dest"
  cp -R "$SRC/." "$dest/"
  echo "synced -> $dest"
}

sync_copy "$ROOT/.agents/skills/$SKILL_NAME"
sync_copy "$ROOT/.opencode/skills/$SKILL_NAME"

CURSOR_RULE="$ROOT/.cursor/rules/$SKILL_NAME.mdc"
mkdir -p "$(dirname "$CURSOR_RULE")"
{
  echo "<!-- generated by scripts/sync-skill-runtimes.sh from .claude/skills/$SKILL_NAME/SKILL.md — do not hand-edit -->"
  echo "<!-- source of truth: .claude/skills/$SKILL_NAME/SKILL.md -->"
  echo
  cat "$SRC/SKILL.md"
} > "$CURSOR_RULE"
echo "synced -> $CURSOR_RULE"
