import { randomUUID } from "node:crypto";
import { describe, expect, it } from "vitest";
import { issueApiKey, revokeApiKey } from "@/lib/admin/keys";
import { getPool } from "@/lib/db/pg/pool";
import { db, seedTeam, sha, type Seed } from "./helpers";

/**
 * AIO-1217 — NATIVE API-KEY OWNER against real Postgres: what the two `lib/admin/keys.ts` primitives
 * `issueApiKey` and `revokeApiKey` themselves write, called directly over synthetic team, member and
 * key rows in the task's data-mechanics Postgres, with the real `lib/api/audit.ts` writer beneath them.
 * This is the native complement of `aio1217-admin-guard-association.datamechanics.test.ts`, where the
 * same two primitives are recording seams: that file shows the wrappers are bound to the gate and
 * executes nothing beneath them; this one executes what is beneath them and nothing above.
 *
 *   1  — issue for a same-team member: the credential's shape, the whole stored row, the one audit row.
 *   2  — revoke a real row: that row alone, its same-member peer and another team's key untouched.
 *   3  — OBSERVED: revoke with another team's row id under the first team id.
 *   4a — issue for a member id that does not exist: the insert is refused, nothing is written.
 *   4b — OBSERVED: issue for a member of ANOTHER team under the first team id.
 *   5  — OBSERVED: revoke with a row id that does not exist.
 *   Z  — what this file does not supply, as executable TODOs naming the owner.
 *
 * What is real, and never mocked: the two primitives, `audit`, the query builder, the pg pool and
 * Postgres. There is no seam in this file. Every observation is a whole-rowset difference of
 * `api_keys` and `audit_log`, read from the pool by raw SQL before and after the one call, so
 * "exactly one row" is a statement about the whole table and not about a filtered read.
 *
 * THE ACTOR IS SUPPLIED, NOT AUTHORIZED. The primitives' own contract is "caller does authz": they
 * take `opts.actor` as given and write it into the audit row. The actor here is a second member row
 * of the acting team, distinct from every key's member, so an audit row that named the wrong one
 * would show. Nothing in this file decides whether that actor may issue or revoke anything.
 *
 * CREDENTIAL HYGIENE. Each credential is generated by the real primitive against the synthetic test
 * database and is usable nowhere else. The raw string and its secret live only inside `issue()`:
 * they are reduced there to booleans and a sha256 and are never returned, logged, bound into a SQL
 * parameter or placed in an assertion, so a failing assertion prints a key id and a hash at most.
 * The rejected and observed issue calls go through `keyIdOnly`, which drops the credential.
 *
 * Bounds of what is claimed.
 *   - NATIVE OWNER BEHAVIOR ONLY. Direct calls of the primitives: not Next action-wire, not POST
 *     dispatch, not `requireTeamAdmin` admission or denial, not revalidation. The action-to-guard
 *     association of `app/t/[team]/admin/actions.ts#issueApiKey` and `#revokeApiKey` is the
 *     association file's evidence and is neither repeated nor extended here.
 *   - AIO-1226 STAYS DEFERRED. The `issueApiKey` action forwards a client-supplied `memberId` with no
 *     same-team lookup of that member. No lookup is added, no target policy is specified and none is
 *     passed. Case 4a is a native write failure; case 4b records that neither the primitive nor the
 *     schema relates a key's team to its member's team today. Neither is the action's target policy.
 *   - CASES 3, 4b AND 5 ARE OBSERVATIONS. `revokeApiKey` matches on row id AND team id, checks no
 *     affected-row count and audits unconditionally, so a call that changes no row still resolves and
 *     still appends an `api_key.revoked` row naming the id it was handed. That is recorded as it is.
 *     It is not a target-binding refusal, not an authorization pass, and not declared correct.
 *   - `api_keys` holds two single-column foreign keys (team → teams, member → members) and none over
 *     the pair. Case 4b reads that back from the catalog before it observes anything.
 *   - `audit` is best-effort and never throws. Only its success is observed: an audit write that
 *     failed would show as a missing row, and no audit-failure behavior is exercised.
 *   - `revokeOwnApiKey` is `self-serve-api-keys.datamechanics.test.ts`'s and is not exercised here.
 *
 * Run status at authoring: NOT RUN. This file was written without executing vitest, tsc or any other
 * command. Its expectations come from reading the sources above, not from an observed run; replace
 * this paragraph with the observed result once it has been executed.
 */

const FIXTURE = "FIXTURE PREMISE FAILED (setup, not an owner observation):";
const CONTROL = "ADMITTED CONTROL FAILED (the paired observation would be vacuous):";

type Row = Record<string, unknown>;

/** Two teams, several issued keys, and whole-rowset snapshots around each call. */
const ROOMY = 30_000;

/** `randomBytes(6)` as hex and `randomBytes(32)` as unpadded base64url: what the primitive generates. */
const KEY_ID = /^[0-9a-f]{12}$/;
const SECRET = /^[A-Za-z0-9_-]{43}$/;

interface World {
  a: Seed;
  b: Seed;
  /** A second active member of team A: the actor every team-A call is supplied with. */
  actor: string;
}

/** How a call ended: what it returned, or how its rejection classifies. */
type Settled = { returned: unknown } | { rejected: { error: boolean; message: string } };

interface Seen {
  outcome: Settled;
  before: Durable;
  after: Durable;
  changed: Changed;
  /** This process's clock immediately around the call. */
  window: { earliest: number; latest: number };
}

/** One admitted issue, with the credential already reduced to what may be compared and printed. */
interface Issued {
  keyId: string;
  /** Whether the returned credential was exactly `aios_<returned key id>_<secret>`. */
  wellFormed: boolean;
  /** sha256 of the secret part alone: what the row may hold. */
  secretSha256: string;
  /** Whether the raw credential or its secret occurs in any `api_keys` or `audit_log` value afterwards. */
  persistedRaw: boolean;
  changed: Changed;
}

// ── fixture plumbing ─────────────────────────────────────────────────────────────────────────────

async function fx<T extends Row = Row>(label: string, text: string, params: unknown[] = []): Promise<T[]> {
  try {
    return (await getPool().query(text, params)).rows as T[];
  } catch (error) {
    throw new Error(`${FIXTURE} ${label}: ${error instanceof Error ? error.message : String(error)}`);
  }
}

async function fxOne<T extends Row = Row>(label: string, text: string, params: unknown[] = []): Promise<T> {
  const rows = await fx<T>(label, text, params);
  if (rows.length !== 1) throw new Error(`${FIXTURE} ${label}: expected exactly one row, got ${rows.length}`);
  return rows[0];
}

function premise(label: string, actual: unknown, expected: unknown): void {
  expect(actual, `${FIXTURE} ${label}`).toEqual(expected);
}

// The two tables the primitives write.
const OWNED_TABLES = ["api_keys", "audit_log"] as const;
type OwnedTable = (typeof OWNED_TABLES)[number];
type Durable = Record<OwnedTable, Row[]>;
type Changed = Partial<Record<OwnedTable, { added: Row[]; removed: Row[] }>>;

/** Every row of both tables, every column, in an order that depends on content only. */
async function durable(): Promise<Durable> {
  const snapshot = {} as Durable;
  for (const table of OWNED_TABLES) {
    const rows = await fx<{ row: Row }>(
      `${table} snapshot`,
      `select to_jsonb(t) as row from ${table} t order by to_jsonb(t)::text`,
    );
    snapshot[table] = rows.map((entry) => entry.row);
  }
  return snapshot;
}

/** The rows a call added and removed, per table; a changed row is one of each. Empty when none. */
function changes(before: Durable, after: Durable): Changed {
  const changed: Changed = {};
  for (const table of OWNED_TABLES) {
    const was = new Set(before[table].map((row) => JSON.stringify(row)));
    const is = new Set(after[table].map((row) => JSON.stringify(row)));
    const added = after[table].filter((row) => !was.has(JSON.stringify(row)));
    const removed = before[table].filter((row) => !is.has(JSON.stringify(row)));
    if (added.length > 0 || removed.length > 0) changed[table] = { added, removed };
  }
  return changed;
}

/** A second active member of the team. Supplied to the primitives as the actor; authorized by nothing. */
async function seedActor(team: Seed): Promise<string> {
  const { data, error } = await db()
    .from("members")
    .insert({
      team_id: team.teamId,
      email: `${randomUUID()}@test.local`,
      display_name: "AIO1217 supplied actor",
      actor_handle: `actor-${randomUUID().slice(0, 8)}`,
      role: "member",
      tier: "team",
      status: "active",
    })
    .select("id")
    .single();
  if (error || !data) throw new Error(`${FIXTURE} actor insert: ${error?.message}`);
  return (data as { id: string }).id;
}

/** Two teams, each with its seeded member. The other team's rows are bystanders. */
async function seedWorld(): Promise<World> {
  const a = await seedTeam();
  const b = await seedTeam();
  premise("the two teams and their members are distinct", [a.teamId === b.teamId, a.memberId === b.memberId], [
    false,
    false,
  ]);
  const actor = await seedActor(a);
  premise("the supplied actor is not team A's seeded member", actor === a.memberId, false);
  return { a, b, actor };
}

const teamOfMember = async (memberId: string): Promise<unknown> =>
  (await fxOne("member team readback", `select team_id from members where id = $1`, [memberId])).team_id;

const teamOfKey = async (rowId: string): Promise<unknown> =>
  (await fxOne("key team readback", `select team_id from api_keys where id = $1`, [rowId])).team_id;

/** Each named key row as the pool reads it back: live while `revoked_at` is null. */
async function liveness(rows: Record<string, string>): Promise<Record<string, string>> {
  const read: Record<string, string> = {};
  for (const [label, id] of Object.entries(rows)) {
    const { revoked_at } = await fxOne<{ revoked_at: Date | null }>(
      `${label} key readback`,
      `select revoked_at from api_keys where id = $1`,
      [id],
    );
    read[label] = revoked_at === null ? "live" : "revoked";
  }
  return read;
}

function rowOf(snapshot: Durable, rowId: string): Row {
  const row = snapshot.api_keys.find((candidate) => candidate.id === rowId);
  if (!row) throw new Error(`${FIXTURE} no api_keys row ${rowId} in the snapshot`);
  return row;
}

// ── the calls ────────────────────────────────────────────────────────────────────────────────────

/** The option both primitives take: the supplied member as the actor. */
const actorOf = (memberId: string) => ({ actor: { kind: "member" as const, memberId } });

async function settle(start: () => Promise<unknown>): Promise<Settled> {
  try {
    return { returned: await start() };
  } catch (thrown) {
    return {
      rejected: { error: thrown instanceof Error, message: thrown instanceof Error ? thrown.message : String(thrown) },
    };
  }
}

/** Snapshot, run the one call, snapshot again. */
async function observe(start: () => Promise<unknown>): Promise<Seen> {
  const before = await durable();
  const earliest = Date.now();
  const outcome = await settle(start);
  const latest = Date.now();
  const after = await durable();
  return { outcome, before, after, changed: changes(before, after), window: { earliest, latest } };
}

/** An issue call reduced to its key id, so no settled outcome can carry the credential. */
const keyIdOnly = async (call: Promise<{ key: string; keyId: string }>): Promise<{ keyId: string }> => ({
  keyId: (await call).keyId,
});

/**
 * One real `issueApiKey` call that must be admitted, and everything that may be said about its
 * credential. The raw string and its secret do not leave this function.
 */
async function issue(teamId: string, memberId: string, name: string, actor: string): Promise<Issued> {
  const before = await durable();
  const { key, keyId } = await issueApiKey(db(), teamId, memberId, name, actorOf(actor));
  const after = await durable();

  const prefix = `aios_${keyId}_`;
  const secret = key.startsWith(prefix) ? key.slice(prefix.length) : key;
  // Compared in this process only: the secret is never bound into a statement.
  const persisted = JSON.stringify(after);
  return {
    keyId,
    wellFormed: key.startsWith(prefix) && KEY_ID.test(keyId) && SECRET.test(secret),
    secretSha256: sha(secret),
    persistedRaw: persisted.includes(key) || persisted.includes(secret),
    changed: changes(before, after),
  };
}

/** A fixture key issued by the real primitive, as the `api_keys` row id a revoke is handed. */
async function issuedRow(teamId: string, memberId: string, name: string, actor: string): Promise<string> {
  const { keyId } = await issue(teamId, memberId, name, actor);
  return (await fxOne<{ id: string }>("issued row id", `select id from api_keys where key_id = $1`, [keyId])).id;
}

// ── what a call leaves behind ────────────────────────────────────────────────────────────────────

/** The whole `api_keys` row of a live key: every column the table has. */
const keyRow = (teamId: string, memberId: string, issued: Issued, name: string): Row => ({
  id: expect.any(String),
  team_id: teamId,
  member_id: memberId,
  key_id: issued.keyId,
  key_hash: issued.secretSha256,
  name,
  created_at: expect.any(String),
  last_used_at: null,
  revoked_at: null,
});

/** The whole `audit_log` row either primitive appends for a supplied member actor. */
const auditRow = (teamId: string, actor: string, action: string, targetId: string, meta: Row): Row => ({
  id: expect.any(Number),
  team_id: teamId,
  actor_kind: "member",
  member_id: actor,
  api_key_id: null,
  action,
  target_type: "api_key",
  target_id: targetId,
  meta,
  ip: null,
  created_at: expect.any(String),
});

/**
 * An admitted issue: a well-formed credential, exactly one new key row holding the returned key id,
 * the given team and member, the given stored name and the sha256 of the secret alone, exactly one
 * new `api_key.issued` audit row, and the raw credential in neither table.
 */
function expectIssued(
  issued: Issued,
  expected: { teamId: string; memberId: string; storedName: string; actor: string },
  label: string,
): void {
  expect(
    { wellFormed: issued.wellFormed, persistedRaw: issued.persistedRaw, changed: issued.changed },
    label,
  ).toEqual({
    wellFormed: true,
    persistedRaw: false,
    changed: {
      api_keys: {
        added: [keyRow(expected.teamId, expected.memberId, issued, expected.storedName)],
        removed: [],
      },
      audit_log: {
        added: [
          auditRow(expected.teamId, expected.actor, "api_key.issued", issued.keyId, {
            for_member: expected.memberId,
          }),
        ],
        removed: [],
      },
    },
  });
}

/** The foreign keys `postgres/schema.sql` declares on `api_keys`: one per column, none over the pair. */
const API_KEY_FOREIGN_KEYS = [
  { conname: "api_keys_member_id_fkey", def: "FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE" },
  { conname: "api_keys_team_id_fkey", def: "FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE" },
];

const apiKeyForeignKeys = (): Promise<Row[]> =>
  fx(
    "api_keys foreign key catalog readback",
    `select conname::text as conname, pg_get_constraintdef(oid) as def
       from pg_constraint
      where conrelid = 'api_keys'::regclass and contype = 'f'
      order by conname`,
  );

/**
 * What Postgres itself answers a raw insert of this team and member pair with: the SQLSTATE and the
 * constraint, read off the driver's error. The values are labels, not key material.
 */
async function nativeRefusalOf(teamId: string, memberId: string): Promise<Row> {
  try {
    await getPool().query(
      `insert into api_keys(team_id, member_id, key_id, key_hash, name) values($1, $2, $3, $4, $5)`,
      [
        teamId,
        memberId,
        `probe-${randomUUID().slice(0, 8)}`,
        sha("aio1217 native owner probe: not a credential"),
        "AIO1217 native owner probe",
      ],
    );
    return { inserted: true };
  } catch (error) {
    const refused = error as { code?: unknown; table?: unknown; constraint?: unknown };
    return { code: refused.code, table: refused.table, constraint: refused.constraint };
  }
}

describe("AIO-1217 native API-key owner — lib/admin/keys issueApiKey and revokeApiKey over real Postgres (direct calls: no action, no guard, no seam)", () => {
  it(
    "1 — issue for a same-team seeded member: the credential is `aios_<key id>_<secret>`; exactly one api_keys row holds the returned key id, that team and member, the normalized name and the sha256 of the secret alone; exactly one `api_key.issued` audit row names the supplied member actor, the key id as target and `meta.for_member`; the raw credential and its secret are in neither table",
    async () => {
      const world = await seedWorld();
      const target = { teamId: world.a.teamId, memberId: world.a.memberId, actor: world.actor };

      // Surrounding whitespace is trimmed before the name is stored.
      const named = await issue(world.a.teamId, world.a.memberId, "  AIO1217 native owner key  ", world.actor);
      expectIssued(named, { ...target, storedName: "AIO1217 native owner key" }, "a padded name");

      // A name that trims to nothing is stored as the primitive's default.
      const unnamed = await issue(world.a.teamId, world.a.memberId, "   ", world.actor);
      expectIssued(unnamed, { ...target, storedName: "unnamed key" }, "a whitespace-only name");

      expect(named.keyId === unnamed.keyId, "two issues share no key id").toBe(false);
      expect(named.secretSha256 === unnamed.secretSha256, "two issues share no secret").toBe(false);
    },
    ROOMY,
  );

  it(
    "2 — revoke a real row through revokeApiKey: only that row gains `revoked_at`, stamped within the call, with every other column as it was; the same member's other key and another team's key stay live; exactly one `api_key.revoked` audit row carries the supplied actor and the target row id",
    async () => {
      const world = await seedWorld();
      const rows = {
        target: await issuedRow(world.a.teamId, world.a.memberId, "AIO1217 native owner target", world.actor),
        // The nearest neighbor a revoke could over-reach to: same team, same member, another row id.
        peer: await issuedRow(world.a.teamId, world.a.memberId, "AIO1217 native owner peer", world.actor),
        otherTeam: await issuedRow(world.b.teamId, world.b.memberId, "AIO1217 native owner bystander", world.b.memberId),
      };
      premise("all three keys start live", await liveness(rows), { target: "live", peer: "live", otherTeam: "live" });

      const seen = await observe(() => revokeApiKey(db(), world.a.teamId, rows.target, actorOf(world.actor)));

      const live = rowOf(seen.before, rows.target);
      expect({ outcome: seen.outcome, changed: seen.changed, liveness: await liveness(rows) }).toEqual({
        outcome: { returned: undefined },
        changed: {
          api_keys: { added: [{ ...live, revoked_at: expect.any(String) }], removed: [live] },
          audit_log: {
            added: [auditRow(world.a.teamId, world.actor, "api_key.revoked", rows.target, {})],
            removed: [],
          },
        },
        liveness: { target: "revoked", peer: "live", otherTeam: "live" },
      });

      // The stamp is this call's own `new Date()`, not an earlier one's.
      const stamped = Date.parse(String(rowOf(seen.after, rows.target).revoked_at));
      expect(stamped).toBeGreaterThanOrEqual(seen.window.earliest);
      expect(stamped).toBeLessThanOrEqual(seen.window.latest);
    },
    ROOMY,
  );

  it(
    "3 — OBSERVED, neither a target-binding refusal nor an authorization pass: revokeApiKey handed another team's row id under the first team id resolves, changes no api_keys row — the other team's key stays live — and still appends one `api_key.revoked` audit row under the first team naming that foreign row id; the same row id under its own team id is then revoked",
    async () => {
      const world = await seedWorld();
      const rows = {
        own: await issuedRow(world.a.teamId, world.a.memberId, "AIO1217 native owner own", world.actor),
        foreign: await issuedRow(world.b.teamId, world.b.memberId, "AIO1217 native owner foreign", world.b.memberId),
      };
      premise("the foreign row is team B's", await teamOfKey(rows.foreign), world.b.teamId);

      const seen = await observe(() => revokeApiKey(db(), world.a.teamId, rows.foreign, actorOf(world.actor)));

      expect({ outcome: seen.outcome, changed: seen.changed, liveness: await liveness(rows) }).toEqual({
        // No error, no return value: the primitive does not read how many rows its UPDATE matched.
        outcome: { returned: undefined },
        // No key row changed, and the audit write occurred all the same.
        changed: {
          audit_log: {
            added: [auditRow(world.a.teamId, world.actor, "api_key.revoked", rows.foreign, {})],
            removed: [],
          },
        },
        liveness: { own: "live", foreign: "live" },
      });

      // The row id was real and revocable: what matched no row above was the UPDATE's team equality.
      const control = await observe(() => revokeApiKey(db(), world.b.teamId, rows.foreign, actorOf(world.b.memberId)));
      expect({ outcome: control.outcome, liveness: await liveness(rows) }, CONTROL).toEqual({
        outcome: { returned: undefined },
        liveness: { own: "live", foreign: "revoked" },
      });
    },
    ROOMY,
  );

  it(
    "4a — issue for a member id that does not exist: after an admitted control on the same team, the call rejects as the primitive's own `issue key failed` error, api_keys and audit_log are unchanged, and Postgres answers the same team and member pair with a foreign-key violation on the member column (a native write failure — NOT the issueApiKey action's same-team target policy, which stays DEFERRED AIO-1226)",
    async () => {
      const world = await seedWorld();
      const control = await issue(world.a.teamId, world.a.memberId, "AIO1217 native owner control", world.actor);
      expectIssued(
        control,
        {
          teamId: world.a.teamId,
          memberId: world.a.memberId,
          storedName: "AIO1217 native owner control",
          actor: world.actor,
        },
        CONTROL,
      );

      const absent = randomUUID();
      premise(
        "no member row has the absent id",
        await fx("absent member readback", `select id from members where id = $1`, [absent]),
        [],
      );

      const seen = await observe(() =>
        keyIdOnly(issueApiKey(db(), world.a.teamId, absent, "AIO1217 native owner absent member", actorOf(world.actor))),
      );

      expect({ outcome: seen.outcome, changed: seen.changed }).toEqual({
        outcome: { rejected: { error: true, message: expect.stringMatching(/^issue key failed: .+/) } },
        // The insert failed, and the audit write sits after it: neither table gained a row.
        changed: {},
      });

      // Read after the observation above, so the probe cannot be mistaken for the primitive's write.
      expect(await nativeRefusalOf(world.a.teamId, absent)).toEqual({
        code: "23503",
        table: "api_keys",
        constraint: "api_keys_member_id_fkey",
      });
    },
    ROOMY,
  );

  it(
    "4b — OBSERVED, not a refusal and not a pass of any target policy: api_keys holds one foreign key per column and none relating a key's team to its member's team, and the primitive performs no lookup of its own — so issue under the first team id for a member of ANOTHER team is not rejected: one api_keys row is written holding the first team with the other team's member, and one `api_key.issued` audit row records it (the same-team member-target refusal is DEFERRED AIO-1226: neither asserted nor implemented here)",
    async () => {
      const world = await seedWorld();
      premise("the target member is team B's", await teamOfMember(world.b.memberId), world.b.teamId);

      // The whole set: a constraint over (team_id, member_id) would be a third entry here.
      expect(await apiKeyForeignKeys(), "the foreign keys Postgres holds on api_keys").toEqual(API_KEY_FOREIGN_KEYS);

      const crossed = await issue(world.a.teamId, world.b.memberId, "AIO1217 native owner cross-team", world.actor);

      expectIssued(
        crossed,
        {
          teamId: world.a.teamId,
          memberId: world.b.memberId,
          storedName: "AIO1217 native owner cross-team",
          actor: world.actor,
        },
        "the cross-team issue as the primitive leaves it today",
      );
    },
    ROOMY,
  );

  it(
    "5 — OBSERVED, no refusal contract is claimed: revokeApiKey handed a row id that does not exist resolves, changes no api_keys row, and still appends one `api_key.revoked` audit row naming that absent id",
    async () => {
      const world = await seedWorld();
      const rows = {
        standing: await issuedRow(world.a.teamId, world.a.memberId, "AIO1217 native owner standing", world.actor),
      };
      const absent = randomUUID();
      premise(
        "no key row has the absent id",
        await fx("absent key readback", `select id from api_keys where id = $1`, [absent]),
        [],
      );

      const seen = await observe(() => revokeApiKey(db(), world.a.teamId, absent, actorOf(world.actor)));

      expect({ outcome: seen.outcome, changed: seen.changed, liveness: await liveness(rows) }).toEqual({
        // A zero-row UPDATE is not an error to the primitive.
        outcome: { returned: undefined },
        changed: {
          audit_log: {
            added: [auditRow(world.a.teamId, world.actor, "api_key.revoked", absent, {})],
            removed: [],
          },
        },
        liveness: { standing: "live" },
      });
    },
    ROOMY,
  );
});

// Each TODO names the owner of evidence this slice was told not to supply.
describe("Z — evidence this file does NOT supply (executable TODOs: none is run, none is passed)", () => {
  it.todo(
    "DEFERRED AIO-1226 · the issueApiKey ACTION forwards a client-supplied memberId with no same-team lookup of that member; case 4b records what the primitive and the schema do with such a pair today, and the desired target refusal is neither asserted nor implemented by this file",
  );
  it.todo(
    "GUARD ASSOCIATION · requireTeamAdmin admission and denial for app/t/[team]/admin/actions.ts#issueApiKey and #revokeApiKey are aio1217-admin-guard-association.datamechanics.test.ts's evidence; this file calls the primitives directly and proves nothing about the wrappers, the action wire or revalidation",
  );
  it.todo(
    "ZERO-ROW REVOKE · whether revokeApiKey should refuse, or withhold its audit row, when its UPDATE matches no row (cases 3 and 5) is not specified by any source this file reads; the current behavior is recorded as observed and no contract for it is declared here",
  );
});
